### ISSUE TITLE
candidate airbnbs

### ISSUE THREAD

**Issue by hackergrrl** [hackergrrl/hackhouse-berlin#1]
Organizing over IRC private chats is hard. Calling @mafintosh @watson @diasdavid @feross

Here are some candidate Berlin airbnbs I managed to find:

---

<s>Buddha apartment: https://www.airbnb.com/rooms/11834992?checkin=04%2F27%2F2016&checkout=05%2F02%2F2016&guests=4&s=oh6Ppp-U

Looks like 3 queen beds and a couch. Themed. $116/night.</s>

Unavailable.

---

Kolle-Belle: https://www.airbnb.com/rooms/11560586?checkin=04%2F27%2F2016&checkout=05%2F02%2F2016&guests=5&s=N8ve8Tfb

2 uncomfortable-looking couches, a double bed, and a queen bed. Posh. $187/night.

---

Apt in Central Berlin: https://www.airbnb.com/rooms/261116?checkin=04%2F27%2F2016&checkout=05%2F02%2F2016&guests=5&s=vm2U5-0y

4 double beds and one couch. Top notch colour coordination. $185/night.

---

Any of these look attractive? Do the dates work? I can go ahead and book if thumbs up from y'all!

**Comment by mafintosh** [comment]
@freeall might be interested as well

**Comment by watson** [comment]
I've made a map where you can see the Squat (the Spektrum pin) and the 3 Airbnb's (A-C): https://drive.google.com/open?id=1U9jO-mJ0uS1X7zsxkQ6nb6wqORg&usp=sharing

Update: Note that the Airbnb pins are not exact since I don't have their precise address

**Comment by watson** [comment]
My gut feeling tell me that we should stay away from the one called "[Large apartment in central Berlin](https://www.airbnb.com/rooms/261116?checkin=04%2F27%2F2016&checkout=05%2F02%2F2016&guests=5&s=vm2U5-0y)"

**Comment by feross** [comment]
I'm cool with any of these.

**Comment by watson** [comment]
I'll arrive on the evening of the 28th and fly out again on the 1st in the morning. This is my flight plan:
https://www.google.dk/flights/#search;f=CPH,ZGH;t=BER,TXL,SXF,QPP;d=2016-04-28;r=2016-05-01;sel=CPHTXL0SK1677,TXLCPH0SK1674;a=STAR_ALLIANCE

**Comment by feross** [comment]
I arrive evening of 26th, leave on morning of 3rd.

**Comment by hackergrrl** [comment]
I'm in on the evening of the 27th, and in Berlin until <_unknown_>.

Maybe we should book {26th or 27th} - 3rd?

**Comment by mafintosh** [comment]
I'm also cool with what whatever decision is made

**Comment by feross** [comment]
Actually, I just changed my plans. Going to Lisbon sounds fun so I'm going to do that! Just canceled my return flight from Berlin.

So, I arrive on the 26th, return indeterminate.

**Comment by hackergrrl** [comment]
Reservation request for Apr 27 - May 2. The host has 24h to respond.

@feross if you (or others) would like it to start on the 26 let me know ASAP and I can change the booking.

**Comment by feross** [comment]
No problem. I can stay in a hostel beforehand :)

**Comment by daviddias** [comment]
@noffle, Thank you for handling the accommodation. I've just booked my flights too :D 

![image](https://cloud.githubusercontent.com/assets/1211152/14764702/d70b671a-09b9-11e6-8420-52d865fb1bd3.png)

@feross you are coming to Lisbon too? Awesome! Are the others also coming? I know @noffle is :) When do you all fly in?

**Comment by feross** [comment]
@diasdavid Yes!

**Comment by freeall** [comment]
I'm thinking about coming Friday 29th afternoon and leaving Sunday 1st evening. Is there room in the apartment?

**Comment by hackergrrl** [comment]
The buddha apartment owner turned down my booking, so we're still hunting for a space that can host the 6 of us. I'm trying to find something, but help on this is welcome!

**Comment by hackergrrl** [comment]
The "Superior Room" of this hotel has 4 beds (2 doubles) and 2 sofas: https://www.booking.com/hotel/de/hotelservicedapartments.en-gb.html?aid=356932;label=metagha-link-localuniversalDE-hotel-68637_dev-desktop_los-1_room-0_lang-en_curr-EUR;sid=20dcad6acd9f8b05113fa20524237f51;dcid=1;checkin=2016-04-27;checkout=2016-05-02;ucfs=1;group_adults=6;group_children=0;req_adults=6;req_children=0;room1=A,A,A,A,A,A;highlighted_blocks=6092315_80716841_0_2,6092304_80716841_4_2;hpos=12;dest_type=city;dest_id=-1746443;srfid=f6a50a47db51de8648ab58c18d4325f9398ae7c1X12#rt-lightbox-open

About US $2000 for 5 nights.

It's getting hard to find things that can fit 6 people this close to May 1, so I think we ought to grab something _schnell_-like.

**Comment by hackergrrl** [comment]
In the interest of reaching a resolution before availabilities were _kaputt_, I booked the above place from Apr 27 to May 2.

It's a 17 minute walk to the U-Bahn, or there's a bus that goes there every 10 minutes. [Google Maps says](https://www.google.com/maps/dir/Invalidenstra%C3%9Fe+32,+10115+Berlin,+Germany/Spektrum,+B%C3%BCrknerstra%C3%9Fe,+Berlin,+Germany/@52.5138888,13.3676032,13z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x47a851ecf1988467:0x44711fc90b3bd494!2m2!1d13.3841818!2d52.5309587!1m5!1m1!1s0x47a84fca120572cf:0x7fc5036b6eb96cd7!2m2!1d13.4229993!2d52.4931578!3e3) ~23 minutes to get to the Squatconf location from the hotel.

---

HSH Hotel Apartments Mitte
Invalidenstr. 32-33, Mitte, Berlin, 10115, Germany

**Comment by hackergrrl** [comment]
Re cost splitting: I figure we each split the cost per night based on who is present. So if there are only 4 of us, we split that night 4 ways, if there are 6 then 6 ways, etc.

**Comment by hackergrrl** [comment]
\o/
